plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'config/sidekiq.yml'

# Disable frozen string literal comment requirement
Style/FrozenStringLiteralComment:
  Enabled: false

# Allow both single and double quotes
Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

# Reasonable line length for modern displays
Layout/LineLength:
  Max: 180
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

# Allow longer methods in specs
Metrics/MethodLength:
  Max: 60
  Exclude:
    - 'spec/**/*'
    - 'db/seeds.rb'
    - 'app/controllers/calendar_controller.rb'  # index method handles calendar and list views

# Allow longer blocks in specs and routes
Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'
    - 'db/seeds.rb'
    - 'app/controllers/*_controller.rb'  # API responses with nested data

# Allow longer classes
Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'spec/**/*'
    - 'app/models/event.rb'  # Core event business logic with many methods
    - 'app/controllers/events_controller.rb'  # Events controller with embed and API actions

# Allow more complex methods (including API controllers with nested JSON)
Metrics/AbcSize:
  Max: 65
  Exclude:
    - 'spec/**/*'
    - 'db/seeds.rb'
    - 'app/controllers/calendar_controller.rb'
    - 'app/controllers/events_controller.rb'
    - 'app/models/user.rb'  # from_omniauth has extensive debug logging
    - 'lib/omniauth/strategies/authentik.rb'  # raw_info has extensive debug logging

# Allow longer example lengths
RSpec/ExampleLength:
  Max: 15

# Allow nested groups
RSpec/NestedGroups:
  Max: 5

# Allow describe class without checking if it's defined
RSpec/DescribeClass:
  Enabled: false

# Documentation is good but not required
Style/Documentation:
  Enabled: false

# Allow empty lines around blocks
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# Allow empty lines in classes
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Allow empty lines in modules
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Rails specific configurations
Rails:
  Enabled: true

# Allow Date.today, Time.now etc in most cases
Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

# Allow has_and_belongs_to_many
Rails/HasAndBelongsToMany:
  Enabled: false

# Don't enforce moving strings to locale files
Rails/I18nLocaleTexts:
  Enabled: false

# Allow various Rails query styles
Rails/WhereRange:
  Enabled: false

# Allow puts in seeds file
Rails/Output:
  Exclude:
    - 'db/seeds.rb'

# Allow JSON.parse over response.parsed_body
Rails/ResponseParsedBody:
  Enabled: false

# RSpec configurations
RSpec/ContextWording:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Max: 10

RSpec/IndexedLet:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

# Allow either do/end or {} for blocks
Style/BlockDelimiters:
  Enabled: false

# Allow duplicate branches in conditionals
Lint/DuplicateBranch:
  Enabled: false

# Allow useless assignments in specs
Lint/UselessAssignment:
  Exclude:
    - 'spec/**/*'

# Allow either STDOUT or $stdout
Style/GlobalStdStream:
  Enabled: false

# More lenient on cyclomatic complexity
Metrics/CyclomaticComplexity:
  Max: 25

# More lenient on perceived complexity
Metrics/PerceivedComplexity:
  Max: 20

# Allow empty conditional bodies (defensive programming)
Lint/EmptyConditionalBody:
  Enabled: false

